HomeWork 5
romankop/SiriusDL pull request #5
Opened 2021-06-20 22:55 UTC by romankop

https://tensorboard.dev/experiment/gmnOAfpfQdqTJkdNIjxQ9g/

Если не работает (но должен!!!), то я пдф версию сайта приложил.

2021-06-22 20:47 UTC, RiskModellingResearch requested changes
Просила ROC AUC считать(

2021-06-23 16:53 UTC, romankop commented
https://tensorboard.dev/experiment/QQm6DQ4pSPy9qCosbSrvWA

2021-06-30 20:03 UTC, RiskModellingResearch commented
Спасибо! Все графики вижу!)

2021-06-30 20:04 UTC, RiskModellingResearch approved these changes
Отлично!

2021-06-30 20:11 UTC, merged